run:
  timeout: 5m
  skip-dirs:
    - terraform/
linters:
  enable:
    - gci
    - gofmt
    - misspell
    - unconvert
    - unparam
issues:
  exclude-rules:
    - path: terraform/
      linters:
        - gosimple
