# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  GO111MODULE: on

steps:
- script: go version
  displayName: 'Go version'

- script: |
    choco install bzr
    set PATH=C:\Program Files (x86)\Bazaar\;%PATH%
    bzr version
  displayName: 'Install Bazaar'

- script: |
    set PATH=C:\Program Files (x86)\Bazaar\;%PATH%
    make build
  displayName: 'make build'
