// This file generated by `tools/api-rule-gen/main.go`. DO NOT EDIT

package api

import (
	"fmt"
	"log"

	"github.com/hashicorp/hcl2/hcl"
	"github.com/wata727/tflint/tflint"
)

// AwsElastiCacheClusterInvalidSubnetGroupRule checks whether attribute value actually exists
type AwsElastiCacheClusterInvalidSubnetGroupRule struct {
	resourceType  string
	attributeName string
	data          map[string]bool
	dataPrepared  bool
}

// NewAwsElastiCacheClusterInvalidSubnetGroupRule returns new rule with default attributes
func NewAwsElastiCacheClusterInvalidSubnetGroupRule() *AwsElastiCacheClusterInvalidSubnetGroupRule {
	return &AwsElastiCacheClusterInvalidSubnetGroupRule{
		resourceType:  "aws_elasticache_cluster",
		attributeName: "subnet_group_name",
		data:          map[string]bool{},
		dataPrepared:  false,
	}
}

// Name returns the rule name
func (r *AwsElastiCacheClusterInvalidSubnetGroupRule) Name() string {
	return "aws_elasticache_cluster_invalid_subnet_group"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsElastiCacheClusterInvalidSubnetGroupRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsElastiCacheClusterInvalidSubnetGroupRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsElastiCacheClusterInvalidSubnetGroupRule) Link() string {
	return ""
}

// Check checks whether the attributes are included in the list retrieved by DescribeCacheSubnetGroups
func (r *AwsElastiCacheClusterInvalidSubnetGroupRule) Check(runner *tflint.Runner) error {
	log.Printf("[INFO] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		if !r.dataPrepared {
			log.Print("[DEBUG] invoking DescribeCacheSubnetGroups")
			var err error
			r.data, err = runner.AwsClient.DescribeCacheSubnetGroups()
			if err != nil {
				err := &tflint.Error{
					Code:    tflint.ExternalAPIError,
					Level:   tflint.ErrorLevel,
					Message: "An error occurred while invoking DescribeCacheSubnetGroups",
					Cause:   err,
				}
				log.Printf("[ERROR] %s", err)
				return err
			}
			r.dataPrepared = true
		}

		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if !r.data[val] {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is invalid subnet group name.`, val),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
