// This file generated by `tools/api-rule-gen/main.go`. DO NOT EDIT

package api

import (
	"fmt"
	"log"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/wata727/tflint/tflint"
)

// AwsRouteInvalidGatewayRule checks whether attribute value actually exists
type AwsRouteInvalidGatewayRule struct {
	resourceType  string
	attributeName string
	data          map[string]bool
	dataPrepared  bool
}

// NewAwsRouteInvalidGatewayRule returns new rule with default attributes
func NewAwsRouteInvalidGatewayRule() *AwsRouteInvalidGatewayRule {
	return &AwsRouteInvalidGatewayRule{
		resourceType:  "aws_route",
		attributeName: "gateway_id",
		data:          map[string]bool{},
		dataPrepared:  false,
	}
}

// Name returns the rule name
func (r *AwsRouteInvalidGatewayRule) Name() string {
	return "aws_route_invalid_gateway"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsRouteInvalidGatewayRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsRouteInvalidGatewayRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsRouteInvalidGatewayRule) Link() string {
	return ""
}

// Check checks whether the attributes are included in the list retrieved by DescribeInternetGateways
func (r *AwsRouteInvalidGatewayRule) Check(runner *tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		if !r.dataPrepared {
			log.Print("[DEBUG] invoking DescribeInternetGateways")
			var err error
			r.data, err = runner.AwsClient.DescribeInternetGateways()
			if err != nil {
				err := &tflint.Error{
					Code:    tflint.ExternalAPIError,
					Level:   tflint.ErrorLevel,
					Message: "An error occurred while invoking DescribeInternetGateways",
					Cause:   err,
				}
				log.Printf("[ERROR] %s", err)
				return err
			}
			r.dataPrepared = true
		}

		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if !r.data[val] {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is invalid internet gateway ID.`, val),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
