// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"log"
	"regexp"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/wata727/tflint/tflint"
)

// AwsTransferUserInvalidServerIDRule checks the pattern is valid
type AwsTransferUserInvalidServerIDRule struct {
	resourceType  string
	attributeName string
	pattern       *regexp.Regexp
}

// NewAwsTransferUserInvalidServerIDRule returns new rule with default attributes
func NewAwsTransferUserInvalidServerIDRule() *AwsTransferUserInvalidServerIDRule {
	return &AwsTransferUserInvalidServerIDRule{
		resourceType:  "aws_transfer_user",
		attributeName: "server_id",
		pattern:       regexp.MustCompile(`^s-([0-9a-f]{17})$`),
	}
}

// Name returns the rule name
func (r *AwsTransferUserInvalidServerIDRule) Name() string {
	return "aws_transfer_user_invalid_server_id"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsTransferUserInvalidServerIDRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsTransferUserInvalidServerIDRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsTransferUserInvalidServerIDRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsTransferUserInvalidServerIDRule) Check(runner *tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if !r.pattern.MatchString(val) {
				runner.EmitIssue(
					r,
					`server_id does not match valid pattern ^s-([0-9a-f]{17})$`,
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
