// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"log"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint/tflint"
)

// AwsIAMOpenidConnectProviderInvalidURLRule checks the pattern is valid
type AwsIAMOpenidConnectProviderInvalidURLRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
}

// NewAwsIAMOpenidConnectProviderInvalidURLRule returns new rule with default attributes
func NewAwsIAMOpenidConnectProviderInvalidURLRule() *AwsIAMOpenidConnectProviderInvalidURLRule {
	return &AwsIAMOpenidConnectProviderInvalidURLRule{
		resourceType:  "aws_iam_openid_connect_provider",
		attributeName: "url",
		max:           255,
		min:           1,
	}
}

// Name returns the rule name
func (r *AwsIAMOpenidConnectProviderInvalidURLRule) Name() string {
	return "aws_iam_openid_connect_provider_invalid_url"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsIAMOpenidConnectProviderInvalidURLRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsIAMOpenidConnectProviderInvalidURLRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsIAMOpenidConnectProviderInvalidURLRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsIAMOpenidConnectProviderInvalidURLRule) Check(runner *tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssue(
					r,
					"url must be 255 characters or less",
					attribute.Expr.Range(),
				)
			}
			if len(val) < r.min {
				runner.EmitIssue(
					r,
					"url must be 1 characters or higher",
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
