// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"log"

	"github.com/hashicorp/hcl2/hcl"
	"github.com/wata727/tflint/tflint"
)

// AwsOrganizationsAccountInvalidIAMUserAccessToBillingRule checks the pattern is valid
type AwsOrganizationsAccountInvalidIAMUserAccessToBillingRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAwsOrganizationsAccountInvalidIAMUserAccessToBillingRule returns new rule with default attributes
func NewAwsOrganizationsAccountInvalidIAMUserAccessToBillingRule() *AwsOrganizationsAccountInvalidIAMUserAccessToBillingRule {
	return &AwsOrganizationsAccountInvalidIAMUserAccessToBillingRule{
		resourceType:  "aws_organizations_account",
		attributeName: "iam_user_access_to_billing",
		enum: []string{
			"ALLOW",
			"DENY",
		},
	}
}

// Name returns the rule name
func (r *AwsOrganizationsAccountInvalidIAMUserAccessToBillingRule) Name() string {
	return "aws_organizations_account_invalid_iam_user_access_to_billing"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsOrganizationsAccountInvalidIAMUserAccessToBillingRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsOrganizationsAccountInvalidIAMUserAccessToBillingRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsOrganizationsAccountInvalidIAMUserAccessToBillingRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsOrganizationsAccountInvalidIAMUserAccessToBillingRule) Check(runner *tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					`iam_user_access_to_billing is not a valid value`,
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
