// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"log"

	"github.com/hashicorp/hcl2/hcl"
	"github.com/wata727/tflint/issue"
	"github.com/wata727/tflint/tflint"
)

// AwsAPIGatewayAuthorizerInvalidTypeRule checks the pattern is valid
type AwsAPIGatewayAuthorizerInvalidTypeRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAwsAPIGatewayAuthorizerInvalidTypeRule returns new rule with default attributes
func NewAwsAPIGatewayAuthorizerInvalidTypeRule() *AwsAPIGatewayAuthorizerInvalidTypeRule {
	return &AwsAPIGatewayAuthorizerInvalidTypeRule{
		resourceType:  "aws_api_gateway_authorizer",
		attributeName: "type",
		enum: []string{
			"TOKEN",
			"REQUEST",
			"COGNITO_USER_POOLS",
		},
	}
}

// Name returns the rule name
func (r *AwsAPIGatewayAuthorizerInvalidTypeRule) Name() string {
	return "aws_api_gateway_authorizer_invalid_type"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsAPIGatewayAuthorizerInvalidTypeRule) Enabled() bool {
	return true
}

// Type returns the rule severity
func (r *AwsAPIGatewayAuthorizerInvalidTypeRule) Type() string {
	return issue.ERROR
}

// Link returns the rule reference link
func (r *AwsAPIGatewayAuthorizerInvalidTypeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsAPIGatewayAuthorizerInvalidTypeRule) Check(runner *tflint.Runner) error {
	log.Printf("[INFO] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					`type is not a valid value`,
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
