// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"log"
	"regexp"

	"github.com/hashicorp/hcl2/hcl"
	"github.com/wata727/tflint/issue"
	"github.com/wata727/tflint/tflint"
)

// AwsTransferUserInvalidRoleRule checks the pattern is valid
type AwsTransferUserInvalidRoleRule struct {
	resourceType  string
	attributeName string
	pattern       *regexp.Regexp
}

// NewAwsTransferUserInvalidRoleRule returns new rule with default attributes
func NewAwsTransferUserInvalidRoleRule() *AwsTransferUserInvalidRoleRule {
	return &AwsTransferUserInvalidRoleRule{
		resourceType:  "aws_transfer_user",
		attributeName: "role",
		pattern:       regexp.MustCompile(`^arn:.*role/.*$`),
	}
}

// Name returns the rule name
func (r *AwsTransferUserInvalidRoleRule) Name() string {
	return "aws_transfer_user_invalid_role"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsTransferUserInvalidRoleRule) Enabled() bool {
	return true
}

// Type returns the rule severity
func (r *AwsTransferUserInvalidRoleRule) Type() string {
	return issue.ERROR
}

// Link returns the rule reference link
func (r *AwsTransferUserInvalidRoleRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsTransferUserInvalidRoleRule) Check(runner *tflint.Runner) error {
	log.Printf("[INFO] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if !r.pattern.MatchString(val) {
				runner.EmitIssue(
					r,
					`role does not match valid pattern ^arn:.*role/.*$`,
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
