// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"log"
	"regexp"

	"github.com/hashicorp/hcl2/hcl"
	"github.com/wata727/tflint/issue"
	"github.com/wata727/tflint/tflint"
)

// AwsIAMRoleInvalidDescriptionRule checks the pattern is valid
type AwsIAMRoleInvalidDescriptionRule struct {
	resourceType  string
	attributeName string
	max           int
	pattern       *regexp.Regexp
}

// NewAwsIAMRoleInvalidDescriptionRule returns new rule with default attributes
func NewAwsIAMRoleInvalidDescriptionRule() *AwsIAMRoleInvalidDescriptionRule {
	return &AwsIAMRoleInvalidDescriptionRule{
		resourceType:  "aws_iam_role",
		attributeName: "description",
		max:           1000,
		pattern:       regexp.MustCompile(`^[\p{L}\p{M}\p{Z}\p{S}\p{N}\p{P}]*$`),
	}
}

// Name returns the rule name
func (r *AwsIAMRoleInvalidDescriptionRule) Name() string {
	return "aws_iam_role_invalid_description"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsIAMRoleInvalidDescriptionRule) Enabled() bool {
	return true
}

// Type returns the rule severity
func (r *AwsIAMRoleInvalidDescriptionRule) Type() string {
	return issue.ERROR
}

// Link returns the rule reference link
func (r *AwsIAMRoleInvalidDescriptionRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsIAMRoleInvalidDescriptionRule) Check(runner *tflint.Runner) error {
	log.Printf("[INFO] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssue(
					r,
					"description must be 1000 characters or less",
					attribute.Expr.Range(),
				)
			}
			if !r.pattern.MatchString(val) {
				runner.EmitIssue(
					r,
					`description does not match valid pattern ^[\p{L}\p{M}\p{Z}\p{S}\p{N}\p{P}]*$`,
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
