// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"log"

	"github.com/hashicorp/hcl2/hcl"
	"github.com/wata727/tflint/issue"
	"github.com/wata727/tflint/tflint"
)

// AwsCloudwatchMetricAlarmInvalidAlarmNameRule checks the pattern is valid
type AwsCloudwatchMetricAlarmInvalidAlarmNameRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
}

// NewAwsCloudwatchMetricAlarmInvalidAlarmNameRule returns new rule with default attributes
func NewAwsCloudwatchMetricAlarmInvalidAlarmNameRule() *AwsCloudwatchMetricAlarmInvalidAlarmNameRule {
	return &AwsCloudwatchMetricAlarmInvalidAlarmNameRule{
		resourceType:  "aws_cloudwatch_metric_alarm",
		attributeName: "alarm_name",
		max:           255,
		min:           1,
	}
}

// Name returns the rule name
func (r *AwsCloudwatchMetricAlarmInvalidAlarmNameRule) Name() string {
	return "aws_cloudwatch_metric_alarm_invalid_alarm_name"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsCloudwatchMetricAlarmInvalidAlarmNameRule) Enabled() bool {
	return true
}

// Type returns the rule severity
func (r *AwsCloudwatchMetricAlarmInvalidAlarmNameRule) Type() string {
	return issue.ERROR
}

// Link returns the rule reference link
func (r *AwsCloudwatchMetricAlarmInvalidAlarmNameRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsCloudwatchMetricAlarmInvalidAlarmNameRule) Check(runner *tflint.Runner) error {
	log.Printf("[INFO] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssue(
					r,
					"alarm_name must be 255 characters or less",
					attribute.Expr.Range(),
				)
			}
			if len(val) < r.min {
				runner.EmitIssue(
					r,
					"alarm_name must be 1 characters or higher",
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
