// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"log"
	"regexp"

	"github.com/hashicorp/hcl2/hcl"
	"github.com/wata727/tflint/issue"
	"github.com/wata727/tflint/tflint"
)

// AwsCloudhsmV2HsmInvalidClusterIDRule checks the pattern is valid
type AwsCloudhsmV2HsmInvalidClusterIDRule struct {
	resourceType  string
	attributeName string
	pattern       *regexp.Regexp
}

// NewAwsCloudhsmV2HsmInvalidClusterIDRule returns new rule with default attributes
func NewAwsCloudhsmV2HsmInvalidClusterIDRule() *AwsCloudhsmV2HsmInvalidClusterIDRule {
	return &AwsCloudhsmV2HsmInvalidClusterIDRule{
		resourceType:  "aws_cloudhsm_v2_hsm",
		attributeName: "cluster_id",
		pattern:       regexp.MustCompile(`^cluster-[2-7a-zA-Z]{11,16}$`),
	}
}

// Name returns the rule name
func (r *AwsCloudhsmV2HsmInvalidClusterIDRule) Name() string {
	return "aws_cloudhsm_v2_hsm_invalid_cluster_id"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsCloudhsmV2HsmInvalidClusterIDRule) Enabled() bool {
	return true
}

// Type returns the rule severity
func (r *AwsCloudhsmV2HsmInvalidClusterIDRule) Type() string {
	return issue.ERROR
}

// Link returns the rule reference link
func (r *AwsCloudhsmV2HsmInvalidClusterIDRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsCloudhsmV2HsmInvalidClusterIDRule) Check(runner *tflint.Runner) error {
	log.Printf("[INFO] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if !r.pattern.MatchString(val) {
				runner.EmitIssue(
					r,
					`cluster_id does not match valid pattern ^cluster-[2-7a-zA-Z]{11,16}$`,
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
