// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"log"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/wata727/tflint/tflint"
)

// AwsLbInvalidIPAddressTypeRule checks the pattern is valid
type AwsLbInvalidIPAddressTypeRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAwsLbInvalidIPAddressTypeRule returns new rule with default attributes
func NewAwsLbInvalidIPAddressTypeRule() *AwsLbInvalidIPAddressTypeRule {
	return &AwsLbInvalidIPAddressTypeRule{
		resourceType:  "aws_lb",
		attributeName: "ip_address_type",
		enum: []string{
			"ipv4",
			"dualstack",
		},
	}
}

// Name returns the rule name
func (r *AwsLbInvalidIPAddressTypeRule) Name() string {
	return "aws_lb_invalid_ip_address_type"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsLbInvalidIPAddressTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsLbInvalidIPAddressTypeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsLbInvalidIPAddressTypeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsLbInvalidIPAddressTypeRule) Check(runner *tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					`ip_address_type is not a valid value`,
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
