// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"log"
	"regexp"

	"github.com/hashicorp/hcl2/hcl"
	"github.com/wata727/tflint/tflint"
)

// AwsDatasyncLocationEfsInvalidSubdirectoryRule checks the pattern is valid
type AwsDatasyncLocationEfsInvalidSubdirectoryRule struct {
	resourceType  string
	attributeName string
	max           int
	pattern       *regexp.Regexp
}

// NewAwsDatasyncLocationEfsInvalidSubdirectoryRule returns new rule with default attributes
func NewAwsDatasyncLocationEfsInvalidSubdirectoryRule() *AwsDatasyncLocationEfsInvalidSubdirectoryRule {
	return &AwsDatasyncLocationEfsInvalidSubdirectoryRule{
		resourceType:  "aws_datasync_location_efs",
		attributeName: "subdirectory",
		max:           4096,
		pattern:       regexp.MustCompile(`^[a-zA-Z0-9_\-\./]*$`),
	}
}

// Name returns the rule name
func (r *AwsDatasyncLocationEfsInvalidSubdirectoryRule) Name() string {
	return "aws_datasync_location_efs_invalid_subdirectory"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsDatasyncLocationEfsInvalidSubdirectoryRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsDatasyncLocationEfsInvalidSubdirectoryRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsDatasyncLocationEfsInvalidSubdirectoryRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsDatasyncLocationEfsInvalidSubdirectoryRule) Check(runner *tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssue(
					r,
					"subdirectory must be 4096 characters or less",
					attribute.Expr.Range(),
				)
			}
			if !r.pattern.MatchString(val) {
				runner.EmitIssue(
					r,
					`subdirectory does not match valid pattern ^[a-zA-Z0-9_\-\./]*$`,
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
