// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"testing"

	"github.com/wata727/tflint/tflint"
)

func Test_AwsEcsServiceInvalidPropagateTagsRule(t *testing.T) {
	cases := []struct {
		Name     string
		Content  string
		Expected tflint.Issues
	}{
		{
			Name: "It includes invalid characters",
			Content: `
resource "aws_ecs_service" "foo" {
	propagate_tags = "CONTAINER"
}`,
			Expected: tflint.Issues{
				{
					Rule:    NewAwsEcsServiceInvalidPropagateTagsRule(),
					Message: `propagate_tags is not a valid value`,
				},
			},
		},
		{
			Name: "It is valid",
			Content: `
resource "aws_ecs_service" "foo" {
	propagate_tags = "SERVICE"
}`,
			Expected: tflint.Issues{},
		},
	}

	rule := NewAwsEcsServiceInvalidPropagateTagsRule()

	for _, tc := range cases {
		runner := tflint.TestRunner(t, map[string]string{"resource.tf": tc.Content})

		if err := rule.Check(runner); err != nil {
			t.Fatalf("Unexpected error occurred: %s", err)
		}

		tflint.AssertIssuesWithoutRange(t, tc.Expected, runner.Issues)
	}
}
