// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"log"

	"github.com/hashicorp/hcl2/hcl"
	"github.com/wata727/tflint/tflint"
)

// AwsConfigOrganizationManagedRuleInvalidRuleIdentifierRule checks the pattern is valid
type AwsConfigOrganizationManagedRuleInvalidRuleIdentifierRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
}

// NewAwsConfigOrganizationManagedRuleInvalidRuleIdentifierRule returns new rule with default attributes
func NewAwsConfigOrganizationManagedRuleInvalidRuleIdentifierRule() *AwsConfigOrganizationManagedRuleInvalidRuleIdentifierRule {
	return &AwsConfigOrganizationManagedRuleInvalidRuleIdentifierRule{
		resourceType:  "aws_config_organization_managed_rule",
		attributeName: "rule_identifier",
		max:           256,
		min:           1,
	}
}

// Name returns the rule name
func (r *AwsConfigOrganizationManagedRuleInvalidRuleIdentifierRule) Name() string {
	return "aws_config_organization_managed_rule_invalid_rule_identifier"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsConfigOrganizationManagedRuleInvalidRuleIdentifierRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsConfigOrganizationManagedRuleInvalidRuleIdentifierRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsConfigOrganizationManagedRuleInvalidRuleIdentifierRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsConfigOrganizationManagedRuleInvalidRuleIdentifierRule) Check(runner *tflint.Runner) error {
	log.Printf("[INFO] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssue(
					r,
					"rule_identifier must be 256 characters or less",
					attribute.Expr.Range(),
				)
			}
			if len(val) < r.min {
				runner.EmitIssue(
					r,
					"rule_identifier must be 1 characters or higher",
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
