// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"fmt"
	"log"
	"regexp"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint/tflint"
)

// AwsSecurityhubStandardsSubscriptionInvalidStandardsArnRule checks the pattern is valid
type AwsSecurityhubStandardsSubscriptionInvalidStandardsArnRule struct {
	resourceType  string
	attributeName string
	pattern       *regexp.Regexp
}

// NewAwsSecurityhubStandardsSubscriptionInvalidStandardsArnRule returns new rule with default attributes
func NewAwsSecurityhubStandardsSubscriptionInvalidStandardsArnRule() *AwsSecurityhubStandardsSubscriptionInvalidStandardsArnRule {
	return &AwsSecurityhubStandardsSubscriptionInvalidStandardsArnRule{
		resourceType:  "aws_securityhub_standards_subscription",
		attributeName: "standards_arn",
		pattern:       regexp.MustCompile(`^.*\S.*$`),
	}
}

// Name returns the rule name
func (r *AwsSecurityhubStandardsSubscriptionInvalidStandardsArnRule) Name() string {
	return "aws_securityhub_standards_subscription_invalid_standards_arn"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsSecurityhubStandardsSubscriptionInvalidStandardsArnRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsSecurityhubStandardsSubscriptionInvalidStandardsArnRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsSecurityhubStandardsSubscriptionInvalidStandardsArnRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsSecurityhubStandardsSubscriptionInvalidStandardsArnRule) Check(runner *tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if !r.pattern.MatchString(val) {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^.*\S.*$`),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
