// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"log"

	"github.com/hashicorp/hcl2/hcl"
	"github.com/wata727/tflint/issue"
	"github.com/wata727/tflint/tflint"
)

// AwsCloudwatchMetricAlarmInvalidAlarmDescriptionRule checks the pattern is valid
type AwsCloudwatchMetricAlarmInvalidAlarmDescriptionRule struct {
	resourceType  string
	attributeName string
	max           int
}

// NewAwsCloudwatchMetricAlarmInvalidAlarmDescriptionRule returns new rule with default attributes
func NewAwsCloudwatchMetricAlarmInvalidAlarmDescriptionRule() *AwsCloudwatchMetricAlarmInvalidAlarmDescriptionRule {
	return &AwsCloudwatchMetricAlarmInvalidAlarmDescriptionRule{
		resourceType:  "aws_cloudwatch_metric_alarm",
		attributeName: "alarm_description",
		max:           1024,
	}
}

// Name returns the rule name
func (r *AwsCloudwatchMetricAlarmInvalidAlarmDescriptionRule) Name() string {
	return "aws_cloudwatch_metric_alarm_invalid_alarm_description"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsCloudwatchMetricAlarmInvalidAlarmDescriptionRule) Enabled() bool {
	return true
}

// Type returns the rule severity
func (r *AwsCloudwatchMetricAlarmInvalidAlarmDescriptionRule) Type() string {
	return issue.ERROR
}

// Link returns the rule reference link
func (r *AwsCloudwatchMetricAlarmInvalidAlarmDescriptionRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsCloudwatchMetricAlarmInvalidAlarmDescriptionRule) Check(runner *tflint.Runner) error {
	log.Printf("[INFO] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssue(
					r,
					"alarm_description must be 1024 characters or less",
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
