// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"log"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint/tflint"
)

// AwsStoragegatewayNfsFileShareInvalidDefaultStorageClassRule checks the pattern is valid
type AwsStoragegatewayNfsFileShareInvalidDefaultStorageClassRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
}

// NewAwsStoragegatewayNfsFileShareInvalidDefaultStorageClassRule returns new rule with default attributes
func NewAwsStoragegatewayNfsFileShareInvalidDefaultStorageClassRule() *AwsStoragegatewayNfsFileShareInvalidDefaultStorageClassRule {
	return &AwsStoragegatewayNfsFileShareInvalidDefaultStorageClassRule{
		resourceType:  "aws_storagegateway_nfs_file_share",
		attributeName: "default_storage_class",
		max:           20,
		min:           5,
	}
}

// Name returns the rule name
func (r *AwsStoragegatewayNfsFileShareInvalidDefaultStorageClassRule) Name() string {
	return "aws_storagegateway_nfs_file_share_invalid_default_storage_class"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsStoragegatewayNfsFileShareInvalidDefaultStorageClassRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsStoragegatewayNfsFileShareInvalidDefaultStorageClassRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsStoragegatewayNfsFileShareInvalidDefaultStorageClassRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsStoragegatewayNfsFileShareInvalidDefaultStorageClassRule) Check(runner *tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssue(
					r,
					"default_storage_class must be 20 characters or less",
					attribute.Expr.Range(),
				)
			}
			if len(val) < r.min {
				runner.EmitIssue(
					r,
					"default_storage_class must be 5 characters or higher",
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
