// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"log"

	"github.com/hashicorp/hcl2/hcl"
	"github.com/wata727/tflint/tflint"
)

// AwsSsmParameterInvalidTypeRule checks the pattern is valid
type AwsSsmParameterInvalidTypeRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAwsSsmParameterInvalidTypeRule returns new rule with default attributes
func NewAwsSsmParameterInvalidTypeRule() *AwsSsmParameterInvalidTypeRule {
	return &AwsSsmParameterInvalidTypeRule{
		resourceType:  "aws_ssm_parameter",
		attributeName: "type",
		enum: []string{
			"String",
			"StringList",
			"SecureString",
		},
	}
}

// Name returns the rule name
func (r *AwsSsmParameterInvalidTypeRule) Name() string {
	return "aws_ssm_parameter_invalid_type"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsSsmParameterInvalidTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsSsmParameterInvalidTypeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsSsmParameterInvalidTypeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsSsmParameterInvalidTypeRule) Check(runner *tflint.Runner) error {
	log.Printf("[INFO] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					`type is not a valid value`,
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
