// This file generated by `tools/model-rule-gen/main.go`. DO NOT EDIT

package models

import (
	"fmt"
	"log"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint/tflint"
)

// AwsAcmpcaCertificateAuthorityInvalidTypeRule checks the pattern is valid
type AwsAcmpcaCertificateAuthorityInvalidTypeRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAwsAcmpcaCertificateAuthorityInvalidTypeRule returns new rule with default attributes
func NewAwsAcmpcaCertificateAuthorityInvalidTypeRule() *AwsAcmpcaCertificateAuthorityInvalidTypeRule {
	return &AwsAcmpcaCertificateAuthorityInvalidTypeRule{
		resourceType:  "aws_acmpca_certificate_authority",
		attributeName: "type",
		enum: []string{
			"ROOT",
			"SUBORDINATE",
		},
	}
}

// Name returns the rule name
func (r *AwsAcmpcaCertificateAuthorityInvalidTypeRule) Name() string {
	return "aws_acmpca_certificate_authority_invalid_type"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsAcmpcaCertificateAuthorityInvalidTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsAcmpcaCertificateAuthorityInvalidTypeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsAcmpcaCertificateAuthorityInvalidTypeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsAcmpcaCertificateAuthorityInvalidTypeRule) Check(runner *tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule for `%s` runner", r.Name(), runner.TFConfigPath())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as type`, val),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
	})
}
