name: generate

on: pull_request

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        submodules: true
    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: 'go.mod'
    - run: go generate ./...
    - run: git add --intent-to-add .
    - run: git diff --exit-code
