name: release

on:
  push:
    branches:
    - '!*'
    tags:
    - v*.*.*

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        submodules: true
    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: 'go.mod'
    - name: Install Cosign
      uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
      with:
        cosign-release: 'v2.6.1'
    - name: Create GitHub App token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      id: app-token
      with:
        client-id: ${{ vars.APP_CLIENT_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        owner: terraform-linters
        repositories: homebrew-tap
        permission-contents: write
        permission-pull-requests: write
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
      with:
        version: v2.11.0
        args: release --release-notes tools/release/release-note.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_APP_TOKEN: ${{ steps.app-token.outputs.token }}
    - uses: actions/attest@a1948c3f048ba23858d222213b7c278aabede763 # v4.1.1
      with:
        subject-path: 'dist/checksums.txt'
